### ISSUE TITLE
来点数据集

### ISSUE THREAD

**Issue by IPNUISTlegal** [raven-dehaze-work/DeblurGanToDehaze#1]
@ravenxrz  同学，能不能来点几千张去雾paired 训练数据集，ITS.zip 44G根本下不动。谢谢

**Comment by ravenxrz** [comment]
@IPNUISTlegal 这个链接里面的ITS数据集是4个多G。
https://pan.baidu.com/s/1iw3Un_Y9iSbhPFPZJHTSoA#list/path=%2F     Passward:  g0s6

**Comment by IPNUISTlegal** [comment]
多谢

**Comment by IPNUISTlegal** [comment]
@ravenxrz  同学，忘了问你。你训练数据集用了多少张？图片尺寸是多少？谢谢

**Comment by ravenxrz** [comment]
size取256*256的， 训练数据集用的ots，把其中的90%用于训练。its数据集未做测试。
 
---原始邮件---
发件人: "lihanyu1204"<notifications@github.com>
发送时间: 2019年6月22日(星期六) 上午9:53
收件人: "raven-dehaze-work/DeblurGanToDehaze"<DeblurGanToDehaze@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"Raven"<zhang.xingrui@foxmail.com>;
主题: Re: [raven-dehaze-work/DeblurGanToDehaze] 来点数据集 (#1)



@ravenxrz  同学，忘了问你。你训练数据集用了多少张？图片尺寸是多少？谢谢

**Comment by ravenxrz** [comment]
@IPNUISTlegal size取256*256的， 训练数据集用的ots，把其中的90%用于训练。its数据集未做测试。

**Comment by IPNUISTlegal** [comment]
@ravenxrz  请问可以加微信，请教你一些问题嘛？lihanyu1204

**Comment by ravenxrz** [comment]
@IPNUISTlegal 尽量用邮箱联系哈，希望理解。
